### ISSUE TITLE
沉浸式状态栏有空隙

### ISSUE THREAD

**Issue by Mitaxing** [yatoooon/AndroidScreenAdaptation#10]
你好，在沉浸式状态栏使用时，部分机型顶部会留有一道空隙，请问是什么问题呢？

**Comment by yatoooon** [comment]
哪个机型,你的布局我看一下

**Comment by Mitaxing** [comment]
Pixel 2和Nexus 4，Pixel 2比Nexus 4会更大些，Pixel则显示正常

**Comment by Mitaxing** [comment]
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/x131"
        android:background="@color/color_car">

        

    </RelativeLayout>


</FrameLayout>

**Comment by yatoooon** [comment]
你用的什么办法实现的沉浸状态栏

**Comment by Mitaxing** [comment]
https://github.com/gyf-dev/ImmersionBar使用的是这个

**Comment by yatoooon** [comment]
你在activity中 ,沉浸方法下面写适配那句话,试一下.

**Comment by yatoooon** [comment]
就是换一下顺序

**Comment by Mitaxing** [comment]
还是同样的效果

**Comment by yatoooon** [comment]
好吧  那我去用一下他的这个库

**Comment by Mitaxing** [comment]
嗯，好了，得先使用您的适配，再使用沉浸式方法就可以了

**Comment by Mitaxing** [comment]
感谢您在百忙中解决我的问题，谢谢

**Comment by yatoooon** [comment]
没事的
