### ISSUE TITLE
Toolbar适配

### ISSUE THREAD

**Issue by Mitaxing** [yatoooon/AndroidScreenAdaptation#11]
在使用Toolbar时，title是适配了，自定义Toolbar按钮也是没问题的，请问Toolbar自带的返回、menu应该如何适配呢？

**Comment by yatoooon** [comment]
自带的返回和menu不适配吗?

**Comment by Mitaxing** [comment]
![image](https://user-images.githubusercontent.com/29652136/38847412-fef6e39e-4233-11e8-98dc-ab90481eaada.png)

**Comment by Mitaxing** [comment]
左边是Toolbar自带的，title目测适配了，右边放大镜图标是自己添加的

**Comment by yatoooon** [comment]
这个原生toolbar   似乎google不想让用户自定义高度,高度就设置为wrapcontent,它里面的这些原生按钮,在源码中都没有设置高度居中

**Comment by yatoooon** [comment]
你可以不用他的返回按钮,自己写一个类似于你放大镜的样子,或者继承它实现一个自定义view

**Comment by Mitaxing** [comment]
嗯嗯，感谢您的建议，谢谢

**Comment by yatoooon** [comment]
网上有这种写法,但是鉴于是反射,用不用在于你自己
public void reSetToolbarHeight(Toolbar toolbar) {
        try {
            Field f = Toolbar.class.getDeclaredField("mNavButtonView");
            f.setAccessible(true);
            ImageButton mNavButtonView = (ImageButton) f.get(toolbar);
            if (mNavButtonView != null) {
                Toolbar.LayoutParams l = (Toolbar.LayoutParams) mNavButtonView.getLayoutParams();
                l.gravity = Gravity.CENTER_VERTICAL;
                mNavButtonView.setLayoutParams(l);
            }
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }
