### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by wrrgit** [yatoooon/AndroidScreenAdaptation#12]
楼主，首先，您的这种写法确实方便省事了很多，感谢分享。
有几点建议：
1、最好再组织下使用方法，让人看了简单明了。
2、建议写出相应的使用方法在CSDN上，方便大家知道有这个东西。
3、不同的分辨率显示的大小不是应该不一样吗，哈，为何看着您的效果图有点一样

**Comment by yatoooon** [comment]
1.步骤已经很简明了
2.csdn不咋地，我也不擅长大篇幅写字
3.适配的最终效果就是看起来都一样啊

**Comment by wrrgit** [comment]
好的，平时做适配比较少，有问题再向您请教
