### ISSUE TITLE
宽度为match_parent，高度为 宽度的 四分之三，这种效果可以设置吗

### ISSUE THREAD

**Issue by tpnet** [yatoooon/AndroidScreenAdaptation#14]
例如Banner，，要适配平板，，高度不能写死。。要根据宽度去计算。。还有RecyclerView的item， @yatoooon

**Comment by yatoooon** [comment]
这种的不用这个库完全可以做啊   比如用约束布局的 constraintDimensionRatio  这个属性 .
RecyclerView的item例子里和步骤上都有说明
