### ISSUE TITLE
关于高度精确度的问题

### ISSUE THREAD

**Issue by liu5241726** [yatoooon/AndroidScreenAdaptation#15]
我看了下代码，设置高度的时候，可能会有问题，设计图宽和高的比例和实际decorview的宽和高比例不一样，在setValue（）方法中，看见的都是以宽度设置为基准的。是不是需要分开算下高度？你这么做是基于什么考虑的？求解答！！！！

**Comment by yatoooon** [comment]
基于不变形不拉伸考虑的,就像一张照片,宽度拉伸到一定值,高度一定是基于宽度变化的比例拉伸才会不变形.

**Comment by yatoooon** [comment]
至于高度出现的问题    可以用matchparent    可以包裹scrollview   可以recyclerview    来做  , 如果要精确的话
可以用约束布局的偏移比例来做

**Comment by liu5241726** [comment]
你说的基于不变形不拉伸，是不是得先要确定设计图纸的的纵横比？我在720 1280的button用的300px 300px，是正方形。在1080  1920模拟器上显示的很显然不是正方形。 我改了下你的代码  把设计稿的高度加上去了，把setvalue方法拆成了两个方法。在宽度方向和高度方向分别进行了setvalue方法比例扩缩。我想知道这个对虚拟按键有影响吗？

**Comment by yatoooon** [comment]
那你就没有用对
