### ISSUE TITLE
有个小疑问，请问核心流程是重新设置LayoutParams么？

### ISSUE THREAD

**Issue by lwlizhe** [yatoooon/AndroidScreenAdaptation#16]
如果是的话，那应该跟autoLayout一样，横纵向都可以一起适配吧，有没有打算连纵向一起适配呢？

**Comment by yatoooon** [comment]
没有打算纵向按纵向的比例来,会产生拉伸形变问题.

**Comment by lwlizhe** [comment]
那这样的话，如果出现纵向超出屏幕范围的情况，有什么好的解决方案么？

**Comment by yatoooon** [comment]
matchparent    scrollview   recyclerview   都是一些常用的解决纵向超出的方案啊

**Comment by lwlizhe** [comment]
哦，只能用一般的解决方式是吧，好的了解了
