### ISSUE TITLE
@yatoooon 这个框架能兼容国产魔改的Pad吗?

### ISSUE THREAD

**Issue by xiexindev** [yatoooon/AndroidScreenAdaptation#17]
我看了一下项目的源代码, 注册是以宽度和dpi值决定适配, 
在实际开发中, 我碰到有一台国产寨板魔改了系统dpi数据, 
一般来说, 一个正常的1080P平板设备的dpi有240是吧, 但是这个魔改Pad把它修改成160了,或者其他的一些数据. 也就是说, 相同尺寸, 相同分辨率, 他的dpi值被魔改成非标准状态了.
 在这样的情况下, 该如何适配呢? 现在用的是AutoLayout, 因为这个框架是基于高宽的分辨率,忽略了dpi,所以没有啥问题
 但是我看到作者您的框架依赖了dpi, 那如果碰到这样的寨版还能适配吗?

**Comment by yatoooon** [comment]
可以的，我的也是基于分辨率的。
