### ISSUE TITLE
动态设置宽高问题

### ISSUE THREAD

**Issue by yxyaxng** [yatoooon/AndroidScreenAdaptation#21]
![x nnas5gond rr gva_p](https://user-images.githubusercontent.com/24906252/42873486-b216a958-8ab1-11e8-9e05-61411df08ab9.png)
动态设置，多次调用ScreenAdapterTools.getInstance().loadView();会多次绘制宽高
举个例子 ，设计图跟实际屏幕的比例为1:2  设置宽度为10，第一次调用，实际宽度为20，第二次调用就变成40

**Comment by yatoooon** [comment]
多次调用适配那句话是这样的效果,     不清楚为什么要对一个动态view多次调用   ,  贴一张效果图瞅瞅

**Comment by yxyaxng** [comment]
其实是这样的，里面有子view，设置好的宽高，外层linerlayout要根据数据进行动态适配，全部控件一次，动态适配一次，至少都要两次，有没有一种只对当前控件进行适配，而子view不动

**Comment by yatoooon** [comment]
子view不适配了吗?   还是子view适配一次   往后就外层linerlayout适配   子view不适配

**Comment by yxyaxng** [comment]
只对当前动态配置的修改就好了

**Comment by yxyaxng** [comment]
或者拿原有的尺寸进行适配，而不是适配过的

**Comment by yatoooon** [comment]
修改版本号   1.1.2      用loadCurrentView(view)  这个方法试下

**Comment by yxyaxng** [comment]
现在的问题是设置的padding算了两次，其实可以参考一下autolayout的处理方式，获取原有尺寸，来进行修改，这样不管多少次调用，只对最后一次生效，这只是我的一个想法，看看大神能不能做出来

**Comment by yatoooon** [comment]
我不可能存一份原有尺寸的 ,至于padding  那就是你的具体问题  ,具体怎么解决看你自己了,我帮不上你
