### ISSUE TITLE
水平方向适配，竖直方向无法适配？

### ISSUE THREAD

**Issue by EvanZch** [yatoooon/AndroidScreenAdaptation#22]
### 设计图纸 1872x1404
基于这个设计图纸写的ui，但是发现在一般手机上，水平方向确实适配很完美，但是竖直方向感觉没有效果，是操作问题还是其他问题，有办法解决吗？望回复，感谢！

**Comment by yatoooon** [comment]
竖直方向也是按水平方向的比例适配的

**Comment by Evan-zch** [comment]
![e0d056c2-60cd-450f-97fc-5051f8098d21](https://user-images.githubusercontent.com/22145615/42934907-e86c9732-8b7a-11e8-97c7-e03e9c458f32.png)
![screenshot_20180719-170815](https://user-images.githubusercontent.com/22145615/42934912-eadd20d6-8b7a-11e8-993a-6125f231e9fa.jpg)
现在是这种情况，难道图纸比例太极端了？

**Comment by yatoooon** [comment]
是新手嘛?,建议你先学几天安卓基础,我不知道怎么和你解释
