### ISSUE TITLE
你这个库在使用上有没有局限性

### ISSUE THREAD

**Issue by yaojunyi3721** [yatoooon/AndroidScreenAdaptation#23]
现在这种百分比布局非常多，用法也大同小异，本质有何区别？
另外其他库都停止维护了，遇到了一些无法解决的问题证明思路不通， 你这个还在更新 是有什么独特的或吸取了前者经验的地方吗？

**Comment by yatoooon** [comment]
本质是我会维护，别人都不维护了，哈哈。

**Comment by yatoooon** [comment]
一句两句也说不清，你体验一下就好了。
