### ISSUE TITLE
你好，这个库在适配TabLayout时应该怎么办啊

### ISSUE THREAD

**Issue by ligong0904** [yatoooon/AndroidScreenAdaptation#25]
项目里有用到TabLayout，发现这个库没法适配TabLayout啊，导致TabLayout内的文字显示效果很差，如下图，适配过的ActionBar和没适配过的TabLayout显示效果差距很大，求指点！
![tim 20180821175203](https://user-images.githubusercontent.com/42509024/44395109-6f2b6a00-a56b-11e8-947b-c5eae62321c4.png)
![tim 20180821175255](https://user-images.githubusercontent.com/42509024/44395111-6f2b6a00-a56b-11e8-96b7-8bce8c4cfbb3.png)
![tim 20180821175411](https://user-images.githubusercontent.com/42509024/44395112-705c9700-a56b-11e8-85e5-d9f60b0b3be1.png)

**Comment by yatoooon** [comment]
不能适配tablayout的字体大小    属性不是android:  而是app:
