### ISSUE TITLE
如果是以高度为基准，这个方案可以适配吗？

### ISSUE THREAD

**Issue by liulianshanzhu** [yatoooon/AndroidScreenAdaptation#26]
如果是以高度为基准，这个方案可以适配吗？

**Comment by liulianshanzhu** [comment]
如何同时兼顾宽高

**Comment by yatoooon** [comment]
我没有做以高度为基准的      在我看来     google已经提供了大量的为高度适配的控件      matchparent     recyclerview   scrollview    constraintlayout

**Comment by JessYanCoding** [comment]
@liulianshanzhu [AndroidAutoSize](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/README-zh.md) 可以支持以高为基准进行适配，并且每个 Activity 和 每个 Fragment 都可以随意切换以高或者以宽为基准进行适配以及每个 Activity 和 每个 Fragment 的设计图尺寸也可以随意定义

**Comment by yatoooon** [comment]
@JessYanCoding  老哥稳
