### ISSUE TITLE
ListView 滑动，item内容(文字、图片)会变大

### ISSUE THREAD

**Issue by lincolnpan** [yatoooon/AndroidScreenAdaptation#27]
Activity里面包含fragment,fragment里面包含listView,大概是这么个布局，滑动的时候item内容会变大。设计图是1080*1920，在2560*1440分辨率的手机里字体或图片变小了，添加适配如下：
Activity里面加了适配"ScreenAdapterTools.getInstance().loadView(getWindow().getDecorView());"
Fragment也加了适配"ScreenAdapterTools.getInstance().loadView(view);"
ListView的adapter里面也加了适配“ScreenAdapterTools.getInstance().loadView(convertView);”

像这种activity里面加了适配，activity所包含的fragment是否也要加，再就是fragment的adapter是否也要加适配？

**Comment by yatoooon** [comment]
是的都得加,   推荐用jessyan的androidautosize库    我现在用的这个

**Comment by lincolnpan** [comment]
老项目，感觉不是很好用
