### ISSUE TITLE
不起效果

### ISSUE THREAD

**Issue by Chenayi** [yatoooon/AndroidScreenAdaptation#3]
刚试了一下，不起效果啊

**Comment by yatoooon** [comment]
按步骤来      确保是按步骤写的

**Comment by Chenayi** [comment]
recyclerview 适配器我使用的是BaseRecyclerViewAdapterHelper，请问在哪里初始化

**Comment by yatoooon** [comment]
recyclerview   demo中有啊   


  @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(testRecyclerViewActivity).inflate(R.layout.test_dp, parent, false);
        ScreenAdapterTools.getInstance().loadView((ViewGroup) view);   //在这里完成对布局的适配
        return new ItemViewHolder(view);
    }

**Comment by Chenayi** [comment]
但是我现在是使用万能适配器BaseRecyclerViewAdapterHelper这个库

**Comment by yatoooon** [comment]
至于BaseRecyclerViewAdapterHelper    我没有用过

**Comment by yatoooon** [comment]
我现在看看这个库是什么

**Comment by Chenayi** [comment]
您方便看看怎么适配吗？因为这个库现在很多人都在用的

**Comment by yatoooon** [comment]
我正在看

**Comment by yatoooon** [comment]
你在你的adapter里面这样写       总之能通过布局填充器得到   view 就好

@Override
    protected View getItemView(int layoutResId, ViewGroup parent) {
        View view = LayoutInflater.from(homeActivity).inflate(layoutResId, parent, false);
        ScreenAdapterTools.getInstance().loadView((ViewGroup) view);
        return view;
    }

**Comment by Chenayi** [comment]
有几个问题想请教一下您，方便加Q聊一下吗，谢谢

**Comment by yatoooon** [comment]
3529161483
