### ISSUE TITLE
如何适配屏幕高度？

### ISSUE THREAD

**Issue by yangyongzhen** [yatoooon/AndroidScreenAdaptation#32]
您好，我在试用该库屏幕适配时，如果屏幕的分辨率是一致的话，则完美适配。但是如果分辨率不一致的话，比如一个是1920*1080，一个是1366*768 ,会导致高度无法适配。有办法解决高度也适配的问题吗？哪怕同比率缩放也行。这样不至于因高度不适配导致某些显示的内容被覆盖了显示不出来

**Comment by yatoooon** [comment]
高度这个问题   所有适配库都是存在的    因为适配只能按照宽度或者高度其中一个来  不然会比例失真  就像androidautolayout库一样  你可以用一下
