### ISSUE TITLE
我拿Demo直接开刀测试的，发现没有效果！

### ISSUE THREAD

**Issue by DevXue** [yatoooon/AndroidScreenAdaptation#7]
项目需求就是一张背景图，然后  把 某个View 移动到这个路上边，然后我用你的Demo直接把TextActivity布局改成我的了  设置了UI 设计图上的px值  发现没有效果。   如下图
![sa](https://user-images.githubusercontent.com/9455329/37860217-ad2e885e-2f5b-11e8-80db-f3e3a2e68748.jpg)

**Comment by DevXue** [comment]
我把manifest.xml改了一下 改成px了    运行效果  有点偏差  不知道什么原因   哥们 能否告知一下
5寸手机上效果有点接近，5.7寸手机效果就有点偏差了
效果图:
![12](https://user-images.githubusercontent.com/9455329/37860276-0a1349d2-2f5d-11e8-9c6b-e1351058d49e.jpg)
![13](https://user-images.githubusercontent.com/9455329/37860280-0db9a6f8-2f5d-11e8-9b2a-f33e46029604.png)

**Comment by yatoooon** [comment]
你的意思是高度没有适配好吗

**Comment by yatoooon** [comment]
是放了好几套图吗     只放一套图    就是你设计图切出来的那套

**Comment by yatoooon** [comment]
还有那张图片的高改成machparent

**Comment by DevXue** [comment]
嗯嗯，说得对   我的 图片就是一张，美工就给了我一张  750*3617的图，  然后我放到了 mipmap-xxhdpi文件夹下面了，  然后运行效果 就是上面那两张图，   5寸屏幕手机接近了， 5.7寸偏下了     难道是我放了一张图片的原因么？

**Comment by yatoooon** [comment]
不是    就应该是放一张图      像你要求这么精确的话     跟美工要一张720宽或者1080宽的吧

**Comment by DevXue** [comment]
@yatoooon   嗯嗯 谢谢哥们，  我先试着把图改成 720  * 1080，然后再看看效果。

**Comment by DevXue** [comment]
@yatoooon   现在忙么？  方便价格QQ讨论么？

**Comment by yatoooon** [comment]
3529161483

**Comment by DevXue** [comment]
多谢大神指点  ，终于搞定了 
 <ScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <FrameLayout
                android:id="@+id/rootViewLl"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                >

                <ImageView
                    android:id="@+id/img1"
                    android:layout_width="720px"
                    android:layout_height="3617px"
                    android:background="@mipmap/bg_sciencesubject01" />



            </FrameLayout>

            <TextView
                android:id="@+id/tv"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="测试"
                android:textStyle="bold"
                android:textColor="@android:color/holo_red_dark"
                android:layout_alignParentRight="true"
                android:layout_marginTop="584px"
                android:textSize="25px"
                />


        </RelativeLayout>

    </ScrollView>

布局文件的ImageView 改成和UI给的图片的宽高一致就可以了！
