### ISSUE TITLE
虚拟按键适配

### ISSUE THREAD

**Issue by Mitaxing** [yatoooon/AndroidScreenAdaptation#8]
请问带有虚拟按键如何适配呢？

**Comment by yatoooon** [comment]
我的库，完全不用管虚拟按键。

**Comment by Mitaxing** [comment]
是这样的，在1080无虚拟按键的手机上是符合设计稿的，但是运行在1080有虚拟按键的手机上就会有部分被页面底部遮挡了

**Comment by yatoooon** [comment]
这是正常的,需要你有一点适配经验,比如在外层包裹一个scrollview

**Comment by yatoooon** [comment]
比如  最外层的高设置为 machparent

**Comment by Mitaxing** [comment]
当前这个页面需要显示全部内容的，scrollview就不太符合了，请问对这种情况如何适配呢？

**Comment by yatoooon** [comment]
最外层的高设置为 machparent 啊
