### ISSUE TITLE
约束布局配合使用出现问题，灰屏了

### ISSUE THREAD

**Issue by drchenzeng** [yatoooon/AndroidScreenAdaptation#9]
我在设计稿(with 750)上画了一个根1px的线，在红米1s(with 720)手机上换算成了0px。然后约束布局0px默认是全屏显示，然后就灰屏了

**Comment by yatoooon** [comment]
给设计师要一份android 的设计图    750的最好不要用

**Comment by yatoooon** [comment]
我修改了一下 ,你依赖1.0.8版本吧

**Comment by drchenzeng** [comment]
了解了，谢谢

**Comment by drchenzeng** [comment]
谢谢，谢谢！
